"""
Test mock business data through the production FastAPI endpoints.

The test performs the real application workflow:

1. Read transcript rows from the mock CSV.
2. Send the first turn of each call without call_id.
3. Save the call ID generated by CockroachDB.
4. Send the remaining transcript turns with that call ID.
5. Read completed-call records from the mock CSV.
6. Replace mock call IDs with the generated CockroachDB IDs.
7. Send completed calls through POST /calls.
8. Use the GET APIs to read the call and transcript data back from CockroachDB.
9. Check that important fields like problem, urgency, follow-up link, and caller details are still correct after saving.

Run FastAPI before running this test:

    uvicorn main:app --reload --port 5050

Then run:

    python -m pytest src/tests/test_mock_api_flow.py -v
"""

import csv
import os
from collections import defaultdict
from pathlib import Path

import httpx
import pytest


# -------------------------------------------------------------------
# Test configuration
# -------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]


# Change these paths when your mock files use different names.
TRANSCRIPT_CSV_FILE = Path(
    os.getenv(
        "MOCK_TRANSCRIPT_CSV",
        PROJECT_ROOT
        / "src"
        / "mock_data"
        / "transcripts.csv"
    )
)


CALLS_CSV_FILE = Path(
    os.getenv(
        "MOCK_CALLS_CSV",
        PROJECT_ROOT
        / "src"
        / "mock_data"
        / "calls.csv"
    )
)


# The production API must be running before this test starts.
API_BASE_URL = os.getenv(
    "API_BASE_URL",
    "http://127.0.0.1:5050",
).rstrip("/")


# Allow OpenAI embedding requests and CockroachDB operations enough time.
REQUEST_TIMEOUT_SECONDS = 60.0


# -------------------------------------------------------------------
# CSV helpers
# -------------------------------------------------------------------

def read_csv_rows(
    file_path: Path,
) -> list[dict[str, str]]:
    """
    Read one CSV file and return its rows as dictionaries.
    """

    if not file_path.exists():
        raise FileNotFoundError(
            f"Mock CSV file was not found: {file_path}"
        )

    with file_path.open(
        mode="r",
        encoding="utf-8-sig",
        newline="",
    ) as csv_file:
        return list(
            csv.DictReader(csv_file)
        )


def clean_optional_value(
    value,
):
    """
    Convert blank CSV values into None.
    """

    if value is None:
        return None

    cleaned_value = str(value).strip()

    if not cleaned_value:
        return None

    return cleaned_value


def require_value(
    row: dict[str, str],
    column_name: str,
) -> str:
    """
    Return one required CSV value.

    Raise a clear error when the column or value is missing.
    """

    if column_name not in row:
        raise KeyError(
            f"CSV column is missing: {column_name}"
        )

    value = clean_optional_value(
        row[column_name]
    )

    if value is None:
        raise ValueError(
            f"CSV value cannot be blank: {column_name}"
        )

    return value


def get_response_record(
    response: httpx.Response,
) -> dict:
    """
    Return the main record from an API response.

    This supports either of these response formats:

        {
            "call_id": "C001",
            ...
        }

    or:

        {
            "message": "...",
            "record": {
                "call_id": "C001",
                ...
            }
        }
    """

    body = response.json()

    for possible_key in (
        "record",
        "transcript",
        "call",
        "data",
    ):
        possible_record = body.get(
            possible_key
        )

        if isinstance(
            possible_record,
            dict,
        ):
            return possible_record

    return body


def find_call_id(
    response: httpx.Response,
) -> str:
    """
    Extract the generated call ID from a transcript API response.
    """

    record = get_response_record(
        response
    )

    call_id = record.get(
        "call_id"
    )

    if not call_id:
        raise AssertionError(
            "The transcript API response did not "
            "contain call_id.\n"
            f"Response: {response.text}"
        )

    return call_id


# -------------------------------------------------------------------
# Payload builders
# -------------------------------------------------------------------

def build_transcript_payload(
    row: dict[str, str],
    generated_call_id: str | None,
) -> dict:
    """
    Convert one transcript CSV row into the production API request.
    """

    payload = {
        "timestamp": require_value(
            row,
            "timestamp",
        ),
        "caller_number": require_value(
            row,
            "caller_number",
        ),
        "speaker": require_value(
            row,
            "speaker",
        ),
        "text": require_value(
            row,
            "text",
        ),
    }

    # The first transcript turn must omit call_id.
    if generated_call_id is not None:
        payload["call_id"] = (
            generated_call_id
        )

    return payload


def build_call_payload(
    row: dict[str, str],
    call_id_mapping: dict[str, str],
) -> dict:
    """
    Convert one completed-call CSV row into the production API request.

    Fixture IDs such as C001 are replaced with the IDs actually
    generated by the production transcript endpoint.
    """

    fixture_call_id = require_value(
        row,
        "call_id",
    )

    generated_call_id = (
        call_id_mapping[
            fixture_call_id
        ]
    )

    fixture_previous_call_id = (
        clean_optional_value(
            row.get(
                "previous_call_id"
            )
        )
    )

    generated_previous_call_id = None

    if fixture_previous_call_id is not None:
        generated_previous_call_id = (
            call_id_mapping[
                fixture_previous_call_id
            ]
        )

    payload = {
        "call_id": generated_call_id,
        "caller_number": require_value(
            row,
            "caller_number",
        ),
        "timestamp": require_value(
            row,
            "timestamp",
        ),
        "name": clean_optional_value(
            row.get("name")
        ),
        "email": clean_optional_value(
            row.get("email")
        ),
        "address": clean_optional_value(
            row.get("address")
        ),
        "problem": clean_optional_value(
            row.get("problem")
        ),
        "problem_detail": clean_optional_value(
            row.get("problem_detail")
        ),
        "availability": clean_optional_value(
            row.get("availability")
        ),
        "urgency": clean_optional_value(
            row.get("urgency")
        ),
        "previous_call_id": (
            generated_previous_call_id
        ),
        "calling_on_behalf_of": (
            clean_optional_value(
                row.get(
                    "calling_on_behalf_of"
                )
            )
        ),
        "summary": clean_optional_value(
            row.get("summary")
        ),
        "ended_at": clean_optional_value(
            row.get("ended_at")
        ),
        "status": (
            clean_optional_value(
                row.get("status")
            )
            or "completed"
        ),
    }

    return payload


# -------------------------------------------------------------------
# Main business-flow test
# -------------------------------------------------------------------

@pytest.mark.integration
def test_mock_business_data_through_production_api():
    """
    Confirm that the mock business data works through the production
    transcript and completed-call endpoints.
    """

    transcript_rows = read_csv_rows(
        TRANSCRIPT_CSV_FILE
    )

    call_rows = read_csv_rows(
        CALLS_CSV_FILE
    )

    assert transcript_rows, (
        "The transcript CSV contains no rows."
    )

    assert call_rows, (
        "The calls CSV contains no rows."
    )

    # Group transcript turns by the fixture call ID.
    transcripts_by_fixture_call_id = (
        defaultdict(list)
    )

    for row in transcript_rows:
        fixture_call_id = require_value(
            row,
            "call_id",
        )

        transcripts_by_fixture_call_id[
            fixture_call_id
        ].append(row)

    # Map fixture IDs to the IDs generated by CockroachDB.
    #
    # Example:
    # {
    #     "C001": "C075",
    #     "C002": "C076"
    # }
    call_id_mapping = {}

    with httpx.Client(
        base_url=API_BASE_URL,
        timeout=REQUEST_TIMEOUT_SECONDS,
    ) as client:

        # Confirm the API is running.
        health_response = client.get(
            "/health"
        )

        assert health_response.status_code == 200, (
            "The FastAPI application is not available at "
            f"{API_BASE_URL}.\n"
            f"Response: {health_response.text}"
        )

        # -----------------------------------------------------------
        # Save all transcript turns through POST /transcripts
        # -----------------------------------------------------------

        for (
            fixture_call_id,
            call_transcript_rows,
        ) in transcripts_by_fixture_call_id.items():

            # Preserve chronological order.
            call_transcript_rows.sort(
                key=lambda row: require_value(
                    row,
                    "timestamp",
                )
            )

            generated_call_id = None

            for row_number, row in enumerate(
                call_transcript_rows
            ):
                payload = (
                    build_transcript_payload(
                        row=row,
                        generated_call_id=(
                            generated_call_id
                        ),
                    )
                )

                response = client.post(
                    "/transcripts",
                    json=payload,
                )

                assert response.status_code in (
                    200,
                    201,
                ), (
                    "Transcript creation failed.\n"
                    f"Fixture call ID: "
                    f"{fixture_call_id}\n"
                    f"Transcript row: "
                    f"{row_number + 1}\n"
                    f"Payload: {payload}\n"
                    f"Response: {response.text}"
                )

                returned_call_id = (
                    find_call_id(
                        response
                    )
                )

                if generated_call_id is None:
                    # Save the ID created for the first turn.
                    generated_call_id = (
                        returned_call_id
                    )

                    call_id_mapping[
                        fixture_call_id
                    ] = generated_call_id

                else:
                    # Every later turn must keep the same call ID.
                    assert (
                        returned_call_id
                        == generated_call_id
                    )

        # Every call in calls.csv must have transcript data.
        fixture_call_ids = {
            require_value(
                row,
                "call_id",
            )
            for row in call_rows
        }

        missing_transcript_call_ids = sorted(
            fixture_call_ids
            - set(call_id_mapping.keys())
        )

        assert not missing_transcript_call_ids, (
            "Some calls do not have transcript data. "
            "Missing transcript call IDs: "
            f"{missing_transcript_call_ids}"
        )

        # -----------------------------------------------------------
        # Save completed calls through POST /calls
        # -----------------------------------------------------------

        remaining_call_rows = (
            call_rows.copy()
        )

        saved_call_rows = []

        # Insert initial calls before follow-up calls.
        while remaining_call_rows:
            inserted_this_round = False

            for row in remaining_call_rows.copy():
                fixture_previous_call_id = (
                    clean_optional_value(
                        row.get(
                            "previous_call_id"
                        )
                    )
                )

                saved_fixture_ids = {
                    require_value(
                        saved_row,
                        "call_id",
                    )
                    for saved_row in saved_call_rows
                }

                previous_call_is_ready = (
                    fixture_previous_call_id
                    is None
                    or fixture_previous_call_id
                    in saved_fixture_ids
                )

                if not previous_call_is_ready:
                    continue

                payload = build_call_payload(
                    row=row,
                    call_id_mapping=(
                        call_id_mapping
                    ),
                )

                response = client.post(
                    "/calls",
                    json=payload,
                )

                assert response.status_code in (
                    200,
                    201,
                ), (
                    "Completed-call creation failed.\n"
                    f"Fixture call ID: "
                    f"{row['call_id']}\n"
                    f"Payload: {payload}\n"
                    f"Response: {response.text}"
                )

                saved_record = (
                    get_response_record(
                        response
                    )
                )

                assert (
                    saved_record["call_id"]
                    == payload["call_id"]
                )

                assert (
                    saved_record[
                        "caller_number"
                    ]
                    == payload[
                        "caller_number"
                    ]
                )

                saved_call_rows.append(
                    row
                )

                remaining_call_rows.remove(
                    row
                )

                inserted_this_round = True

            if not inserted_this_round:
                unresolved_ids = [
                    row["call_id"]
                    for row in (
                        remaining_call_rows
                    )
                ]

                raise AssertionError(
                    "The remaining calls could not be "
                    "inserted. Check their "
                    "previous_call_id values: "
                    f"{unresolved_ids}"
                )

        # -----------------------------------------------------------
        # Retrieve and verify every business call
        # -----------------------------------------------------------

        for row in call_rows:
            fixture_call_id = require_value(
                row,
                "call_id",
            )

            generated_call_id = (
                call_id_mapping[
                    fixture_call_id
                ]
            )

            response = client.get(
                f"/calls/{generated_call_id}"
            )

            assert response.status_code == 200, (
                "Saved call could not be retrieved.\n"
                f"Call ID: {generated_call_id}\n"
                f"Response: {response.text}"
            )

            saved_call = get_response_record(
                response
            )

            assert (
                saved_call["call_id"]
                == generated_call_id
            )

            assert (
                saved_call["caller_number"]
                == require_value(
                    row,
                    "caller_number",
                )
            )

            # Verify important optional business fields.
            for field_name in (
                "problem",
                "problem_detail",
                "availability",
                "urgency",
                "calling_on_behalf_of",
            ):
                expected_value = (
                    clean_optional_value(
                        row.get(
                            field_name
                        )
                    )
                )

                assert (
                    saved_call.get(
                        field_name
                    )
                    == expected_value
                ), (
                    f"Incorrect {field_name} for "
                    f"{fixture_call_id}."
                )

            fixture_previous_call_id = (
                clean_optional_value(
                    row.get(
                        "previous_call_id"
                    )
                )
            )

            expected_previous_call_id = None

            if fixture_previous_call_id:
                expected_previous_call_id = (
                    call_id_mapping[
                        fixture_previous_call_id
                    ]
                )

            assert (
                saved_call.get(
                    "previous_call_id"
                )
                == expected_previous_call_id
            )

            # Confirm transcripts are available through the API.
            transcript_response = client.get(
                "/transcripts",
                params={
                    "call_id": (
                        generated_call_id
                    )
                },
            )

            assert (
                transcript_response.status_code
                == 200
            ), (
                "Transcript retrieval failed.\n"
                f"Call ID: {generated_call_id}\n"
                f"Response: "
                f"{transcript_response.text}"
            )

            transcript_body = (
                transcript_response.json()
            )

            if isinstance(
                transcript_body,
                dict,
            ):
                saved_transcripts = (
                    transcript_body.get(
                        "transcripts",
                        transcript_body.get(
                            "data",
                            [],
                        ),
                    )
                )
            else:
                saved_transcripts = (
                    transcript_body
                )

            expected_transcript_count = len(
                transcripts_by_fixture_call_id[
                    fixture_call_id
                ]
            )

            assert (
                len(saved_transcripts)
                == expected_transcript_count
            ), (
                "Incorrect transcript count.\n"
                f"Fixture call ID: "
                f"{fixture_call_id}\n"
                f"Generated call ID: "
                f"{generated_call_id}\n"
                f"Expected: "
                f"{expected_transcript_count}\n"
                f"Received: "
                f"{len(saved_transcripts)}"
            )

    print()
    print(
        "Mock business data successfully passed "
        "through the production API."
    )
    print(
        f"Transcript calls tested: "
        f"{len(call_id_mapping)}"
    )
    print(
        f"Completed calls tested: "
        f"{len(call_rows)}"
    )